### PR TITLE
Add reference to component's node attribute

### PR DESCRIPTION
**Pull request by joelbyler**
This can be hard to find this in the docs, and can be handy to know.

### CODE REVIEW

**Comment by angus-c** [comment]
Thanks. So as not to break up the `this.select` description I think this would work better in parentheses at the bottom of the section (after the example code). Also I think `can` not `may` might be more accurate:

>(You can access the component's node directly by using the component's node attribute. e.g. `this.node`.)

**Comment by joelbyler** [comment]
@angus-c I've made a second commit to move the note down, does this work for you now? I can squash the commits if you want too.  Let me know, and thanks for the feedback!

**Comment by angus-c** [comment]
Thanks - yes could you squash the commits please.

**Comment by joelbyler** [comment]
@angus-c squashed down to a single commit.  I'd be glad to help out with other things if you need some help with some of these issues.  Feel free to reach out to me! :)

**Comment by angus-c** [comment]
Sure thing (cc @phuu)

**Comment by phuu** [comment]
@angus-c Thanks for dealing with this. Did you mean to merge it?

**Comment by angus-c** [comment]
@phuu whoops yes! thanks

**Pull request merged**
