### PR TITLE
Pass the correct event.currentTarget on delegation

### LINKED ISSUE #290: Why is 'el' added to event data when using the 'this.on' delegate pattern?
The delegate pattern for `this.on` adds `el` to the data:

```js
this.on('eventName', {
  someSelector: f
});

this.f = function (e, data) {
  console.log(data.el);
  // => DOMNode
};
```

Can't work out why. Thanks

### PR DESCRIPTION
**Pull request by giuseppeg**
Removes data.el from the event data payload
Fixes #290

### CODE REVIEW

**Comment by phuu** [comment]
Thanks for this @giuseppeg.

For backward compatibility I'd like to keep `data.el`, otherwise this needs to go out with a major version bump (well, for this semver-ish project it's minor), not to mention a load of refactoring in TweetDeck. Can we just add `currentTarget` and the test?

**Comment by giuseppeg** [comment]
@phuu I guess we can. Let's see what the other people think about it.

**Comment by phuu** [comment]
Gonna close this and cos I've put up another with some fixes (#329) — not sure of a better way to contribute to your pull!

**Comment by giuseppeg** [comment]
sure np

**Pull request closed without merging**
