### PR TITLE
Updated Base.js To keep the context in this.on([selector,] eventType, ha...

### PR DESCRIPTION
**Pull request by aemonge**
...ndler)

I've made a simple  adjustment so the components, mixins, aka our object keep their context closed. My motivation started trying to do recursive components ( such as nested tabs). Hope it helps, if test is needed I'll commit it again with no failing tests ;)

### CODE REVIEW

**Comment by Balder79** [comment]
+1

**Comment by raulgundin** [comment]
+1

**Comment by phuu** [comment]
Thanks alot for this @aemonge. I'm afraid it's something we can't merge as it's a backward incompatible change — for example, it forbids a component to listen on the `document` which is behaviour Flight encourages.

You could however enforce this behaviour in your own code by creating a mixin with the API you want, and mixing it into a new base component. Happy to help out if you'd like to do this.

**Comment by aemonge** [comment]
Ohhh!!!! Backwards compatibility it's a big issue. In other hand, it didn't got the idea that flight encourages me to listen to **document** . But I'm glad I know that =D

Thanks for the quick response.

**Pull request closed without merging**
